/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coding;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author USER
 */
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.swing.JFileChooser;
import java.io.*;
import javax.swing.JOptionPane;

public class Email extends javax.swing.JFrame {
    BufferedImage attachment = null;
    private Object JLabelAttachment;
    /**
     * Creates new form Email
     */String from, to, host, sub, content, path;
    public Email() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabelAttach = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();
        jPanelAttachment = new javax.swing.JPanel();
        jLabelAttachment = new javax.swing.JLabel();
        jPanelReceiver = new javax.swing.JPanel();
        jTextReceiver = new javax.swing.JTextField();
        jPanelBody = new javax.swing.JPanel();
        jTextBody = new javax.swing.JTextField();
        jPanelSubject = new javax.swing.JPanel();
        jTextSubject = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel3.setText("Password :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setFont(new java.awt.Font("Urban Jungle", 1, 60)); // NOI18N
        jTextField1.setText("                    Send     Email");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 665, -1));

        jLabelAttach.setBackground(new java.awt.Color(102, 102, 255));
        jLabelAttach.setText("Attach File");
        jLabelAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelAttachActionPerformed(evt);
            }
        });
        getContentPane().add(jLabelAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jButtonSend.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 507, 140, 69));

        jPanelAttachment.setBackground(new java.awt.Color(153, 153, 255));
        jPanelAttachment.setBorder(javax.swing.BorderFactory.createTitledBorder("Attachment:"));

        javax.swing.GroupLayout jPanelAttachmentLayout = new javax.swing.GroupLayout(jPanelAttachment);
        jPanelAttachment.setLayout(jPanelAttachmentLayout);
        jPanelAttachmentLayout.setHorizontalGroup(
            jPanelAttachmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAttachment, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
        jPanelAttachmentLayout.setVerticalGroup(
            jPanelAttachmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAttachmentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAttachment, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelAttachment, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 439, -1, 190));

        jPanelReceiver.setBackground(new java.awt.Color(153, 153, 255));
        jPanelReceiver.setBorder(javax.swing.BorderFactory.createTitledBorder("Receiver:"));

        javax.swing.GroupLayout jPanelReceiverLayout = new javax.swing.GroupLayout(jPanelReceiver);
        jPanelReceiver.setLayout(jPanelReceiverLayout);
        jPanelReceiverLayout.setHorizontalGroup(
            jPanelReceiverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextReceiver)
        );
        jPanelReceiverLayout.setVerticalGroup(
            jPanelReceiverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextReceiver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 650, -1));

        jPanelBody.setBackground(new java.awt.Color(153, 153, 255));
        jPanelBody.setBorder(javax.swing.BorderFactory.createTitledBorder("Body:"));

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextBody)
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextBody, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 650, -1));

        jPanelSubject.setBackground(new java.awt.Color(153, 153, 255));
        jPanelSubject.setBorder(javax.swing.BorderFactory.createTitledBorder("Subject:"));

        javax.swing.GroupLayout jPanelSubjectLayout = new javax.swing.GroupLayout(jPanelSubject);
        jPanelSubject.setLayout(jPanelSubjectLayout);
        jPanelSubjectLayout.setHorizontalGroup(
            jPanelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextSubject)
        );
        jPanelSubjectLayout.setVerticalGroup(
            jPanelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 650, -1));

        jButtonReset.setBackground(new java.awt.Color(102, 102, 255));
        jButtonReset.setText("Clear");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coding/blue-mountains-vertical-hd-wallpaper-preview.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 670, 570));

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {                                            
        from = "aliffcs251@gmail.com";
        to = jTextReceiver.getText();
        host = "localhost";
        sub = jTextSubject.getText();
        content = jTextBody.getText();
        Properties p =new Properties();
        p.put("mail.smtp.auth", "true");
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.port", "587");
        Session s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication()
            {
                return new PasswordAuthentication("aliffcs251@gmail.com", "ediwjkviknyrtaxb");
            }
        });
        try
        {
            MimeMessage m = new MimeMessage(s);
            Multipart ms = new MimeMultipart();
            MimeBodyPart pdf = new MimeBodyPart();
            m.setFrom(from);
            m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            m.setSubject(sub);
            m.setText(content);
            if (path == null)
            {
            Transport.send(m);
            System.out.println("Success");
            }
            else
            {
                pdf.attachFile(path);
                ms.addBodyPart(pdf);
                m.setContent(ms);
                Transport.send(m);
                JOptionPane.showMessageDialog(this, "Email Successfully Sent!");
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }                                           
    
    private void jLabelAttachActionPerformed(java.awt.event.ActionEvent evt) {                                             
        JFileChooser ch  = new JFileChooser();
        ch.showOpenDialog(null);
        File f = ch.getSelectedFile();
        path = f.getAbsolutePath();
        
        if(f == null){
            return;
        }
        try {
            attachment = ImageIO.read(f);
            jLabelAttachment.setIcon(new ImageIcon (attachment));
            this.validate();
        } catch (IOException ex) {
            
        }
    }                                            

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {                                             
        jTextReceiver.setText("");
        jTextSubject.setText("");
        jTextBody.setText("");
    }                                            

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLabelAttach;
    private javax.swing.JLabel jLabelAttachment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAttachment;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelReceiver;
    private javax.swing.JPanel jPanelSubject;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextBody;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextReceiver;
    private javax.swing.JTextField jTextSubject;
    // End of variables declaration                   
}
